window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10
scrolling:
  # Specifying '0' will disable scrolling.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3
font:
  normal:
    family: Victor Mono
    style: Regular
  bold:
    family: Victor Mono
    style: Bold
  italic:
    family: Victor Mono
    style: Italic
  bold_italic:
    family: Victor Mono
    style: Bold Italic
  size: 10.0
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true
# Base16 Default Dark 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
   primary:
    background: '#1a1b26'
    foreground: '#a9b1d6'

   # Normal colors
   normal:
    black:   '#32344a'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#ad8ee6'
    cyan:    '#449dab'
    white:   '#787c99'

   # Bright colors
   bright:
    black:   '#444b6a'
    red:     '#ff7a93'
    green:   '#b9f27c'
    yellow:  '#ff9e64'
    blue:    '#7da6ff'
    magenta: '#bb9af7'
    cyan:    '#0db9d7'
    white:   '#acb0d0'
shell:
  program: /usr/bin/fish
