vim.keymap.set("n", "<leader>xx", "<cmd>Trouble<cr>", { silent = true, noremap = true })
vim.keymap.set("n", "<leader>xw", "<cmd>Trouble diagnostics toggle<cr>", { silent = true, noremap = true })
vim.keymap.set("n", "<leader>xd", "<cmd>Trouble diagnostics filter.buf=0<cr>", { silent = true, noremap = true })
vim.keymap.set("n", "gr", "<cmd>Trouble lsp_references<cr>", { silent = true, noremap = true })
vim.keymap.set("n", "gd", "<cmd>Trouble lsp_definitions<cr>", { silent = true, noremap = true })
vim.keymap.set("n", "gi", "<cmd>Trouble lsp_implementations<cr>", { silent = true, noremap = true })
vim.keymap.set("n", "gtd", "<cmd>Trouble lsp_type_definitions<cr>", { silent = true, noremap = true })
